name: ci-cd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job-1:
    if: startsWith(github.head_ref, 'hotfix') != true
    name: job-1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script-1
        run: echo Hello, world!

  job-2:
    if: startsWith(github.head_ref, 'hotfix') != true
    name: job-2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script-2
        run: echo Hello, world!
