name: Hotfix

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  job-1:
    name: job-1
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.ref }}

  job-2:
    name: job-2
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.ref }}
