name: Hotfix

on:
  push:
    branches:
      - hotfix/*

jobs:
  build-hotfix:
    name: build-hotfix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
