name: Hotfix

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  get-merged-branch-name:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    outputs:
      merged_branch_name: ${{ steps.branch_name.outputs.merged_branch_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the branch name
        id: branch_name
        run: |
          commit_subject=$(git log -1 --pretty=format:%s)
          echo Commit subject: $commit_subject

          regex='Merge pull request #[0-9]+ from .+/(.+)$'
          [[ $commit_subject =~ $regex ]]
          branch_name=${BASH_REMATCH[1]}
          echo Merged branch: $branch_name
          echo "merged_branch_name=$branch_name" >> $GITHUB_ENV

  job-1:
    name: job-1
    runs-on: ubuntu-latest
    needs: get-merged-branch-name
    environment: hotfix
    if: github.event_name == 'push' && contains(needs.get-merged-branch-name.outputs.merged_branch_name, 'hotfix')
    steps:
      - run: echo Hello

  # job-2:
  #   name: job-2
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push'
  #   steps:
  #     - run: echo ${{ github.head_ref }}
  #     - run: echo ${{ github.ref }}
